Fixed bugs. 1. Added null check condition on Monitor.exit which is required when deoptimization happens in case exception handler was not compiled by Graal compiler while throwing NullPointerException in Monitor.enter 2. Modified assertion as more DeoptimizationReasons are covered by tests. 3. Methods from private top level classes which are siblings of test java classes are loaded to test image to avoid throwing NoClassDefFoundError.